# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-26 15:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import interiit_app.models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sport_Aquatics_Men',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iit_name', models.CharField(choices=[('IITKGP', 'IIT Kharagpur'), ('IITB', 'IIT Bombay'), ('IITK', 'IIT Kanpur'), ('IITM', 'IIT Madras'), ('IITD', 'IIT Delhi'), ('IITG', 'IIT Guhawati'), ('IITR', 'IIT Roorkee'), ('IITBBS', 'IIT Bhubaneshwar'), ('IITGN', 'IIT Gandhinagar'), ('IITH', 'IIT Hyderabad'), ('IITJ', 'IIT Jodhpur'), ('IITP', 'IIT Patna'), ('IITRPR', 'IIT Ropar'), ('IITI', 'IIT Indore'), ('IITMANDI', 'IIT Mandi'), ('IITBHU', 'IIT (BHU) Varanasi'), ('IITPKD', 'IIT Palakkad'), ('IITTP', 'IIT Tirupati'), ('IITISM', 'IIT (ISM) Dhanbad'), ('IITBH', 'IIT Bhilai'), ('IITGOA', 'IIT Goa'), ('IITJM', 'IIT Jammu'), ('IITDH', 'IIT Dharwad')], max_length=10)),
                ('student_name', models.CharField(max_length=50)),
                ('blood_group', models.CharField(max_length=15)),
                ('mobile_no', phonenumber_field.modelfields.PhoneNumberField(max_length=128)),
                ('email', models.EmailField(max_length=254)),
                ('photo', models.ImageField(default=None, null=True, upload_to=interiit_app.models.Sport_Aquatics_Men.path_and_rename)),
                ('arrival', models.CharField(max_length=20)),
                ('departure', models.CharField(max_length=20)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('food', models.CharField(choices=[('VEG', 'Vegetarian'), ('JAIN', 'Jain'), ('NONVEG', 'Non-Vegetarian')], default='VEG', max_length=10)),
                ('water_polo', models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], default='NO', max_length=10)),
                ('free_50m', models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], default='NO', max_length=10)),
                ('free_100m', models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], default='NO', max_length=10)),
                ('free_200m', models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], default='NO', max_length=10)),
                ('free_400m', models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], default='NO', max_length=10)),
                ('free_1500m', models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], default='NO', max_length=10)),
                ('back_50m', models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], default='NO', max_length=10)),
                ('back_100m', models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], default='NO', max_length=10)),
                ('back_200m', models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], default='NO', max_length=10)),
                ('breast_50m', models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], default='NO', max_length=10)),
                ('breast_100m', models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], default='NO', max_length=10)),
                ('breast_200m', models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], default='NO', max_length=10)),
                ('b_fly_50m', models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], default='NO', max_length=10)),
                ('b_fly_100m', models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], default='NO', max_length=10)),
                ('i_m_200m', models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], default='NO', max_length=10)),
                ('free_relay_4x100m', models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], default='NO', max_length=10)),
                ('medley_relay_4x100m', models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], default='NO', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Sport_Aquatics_Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iit_name', models.CharField(choices=[('IITKGP', 'IIT Kharagpur'), ('IITB', 'IIT Bombay'), ('IITK', 'IIT Kanpur'), ('IITM', 'IIT Madras'), ('IITD', 'IIT Delhi'), ('IITG', 'IIT Guhawati'), ('IITR', 'IIT Roorkee'), ('IITBBS', 'IIT Bhubaneshwar'), ('IITGN', 'IIT Gandhinagar'), ('IITH', 'IIT Hyderabad'), ('IITJ', 'IIT Jodhpur'), ('IITP', 'IIT Patna'), ('IITRPR', 'IIT Ropar'), ('IITI', 'IIT Indore'), ('IITMANDI', 'IIT Mandi'), ('IITBHU', 'IIT (BHU) Varanasi'), ('IITPKD', 'IIT Palakkad'), ('IITTP', 'IIT Tirupati'), ('IITISM', 'IIT (ISM) Dhanbad'), ('IITBH', 'IIT Bhilai'), ('IITGOA', 'IIT Goa'), ('IITJM', 'IIT Jammu'), ('IITDH', 'IIT Dharwad')], max_length=10)),
                ('staff_name', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1)),
                ('blood_group', models.CharField(max_length=15)),
                ('mobile_no', phonenumber_field.modelfields.PhoneNumberField(max_length=128)),
                ('email', models.EmailField(max_length=254)),
                ('photo', models.ImageField(default=None, null=True, upload_to=interiit_app.models.Sport_Aquatics_Staff.path_and_rename)),
                ('arrival', models.CharField(max_length=20)),
                ('departure', models.CharField(max_length=20)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('food', models.CharField(choices=[('VEG', 'Vegetarian'), ('JAIN', 'Jain'), ('NONVEG', 'Non-Vegetarian')], default='VEG', max_length=10)),
                ('designation', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Sport_Aquatics_Women',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iit_name', models.CharField(choices=[('IITKGP', 'IIT Kharagpur'), ('IITB', 'IIT Bombay'), ('IITK', 'IIT Kanpur'), ('IITM', 'IIT Madras'), ('IITD', 'IIT Delhi'), ('IITG', 'IIT Guhawati'), ('IITR', 'IIT Roorkee'), ('IITBBS', 'IIT Bhubaneshwar'), ('IITGN', 'IIT Gandhinagar'), ('IITH', 'IIT Hyderabad'), ('IITJ', 'IIT Jodhpur'), ('IITP', 'IIT Patna'), ('IITRPR', 'IIT Ropar'), ('IITI', 'IIT Indore'), ('IITMANDI', 'IIT Mandi'), ('IITBHU', 'IIT (BHU) Varanasi'), ('IITPKD', 'IIT Palakkad'), ('IITTP', 'IIT Tirupati'), ('IITISM', 'IIT (ISM) Dhanbad'), ('IITBH', 'IIT Bhilai'), ('IITGOA', 'IIT Goa'), ('IITJM', 'IIT Jammu'), ('IITDH', 'IIT Dharwad')], max_length=10)),
                ('student_name', models.CharField(max_length=50)),
                ('blood_group', models.CharField(max_length=15)),
                ('mobile_no', phonenumber_field.modelfields.PhoneNumberField(max_length=128)),
                ('email', models.EmailField(max_length=254)),
                ('photo', models.ImageField(default=None, null=True, upload_to=interiit_app.models.Sport_Aquatics_Women.path_and_rename)),
                ('arrival', models.CharField(max_length=20)),
                ('departure', models.CharField(max_length=20)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('food', models.CharField(choices=[('VEG', 'Vegetarian'), ('JAIN', 'Jain'), ('NONVEG', 'Non-Vegetarian')], default='VEG', max_length=10)),
                ('freestyle_50m', models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], default='NO', max_length=10)),
                ('freestyle_100m', models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], default='NO', max_length=10)),
                ('breast_stroke_50m', models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], default='NO', max_length=10)),
                ('back_stroke_50m', models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], default='NO', max_length=10)),
                ('butterfly_50m', models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], default='NO', max_length=10)),
                ('freestyle_relay_4x50m', models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], default='NO', max_length=10)),
            ],
        ),
    ]
